-- Table Schemas
DROP TABLE IF EXISTS hostel_reservations;
DROP TABLE IF EXISTS outdoor_events;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS rooms;
DROP TABLE IF EXISTS event_reservations;
DROP TABLE IF EXISTS hostels;

CREATE TABLE hostels
(
 id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 hostel_name VARCHAR(25) NOT NULL,
 address VARCHAR(250) NOT NULL,
 room_numbers INT NOT NULL
);

CREATE TABLE rooms
(
 id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 hostel_id INT NOT NULL,
 room_name VARCHAR(25) NOT NULL,
 room_floor INT NOT NULL,
 capacity INT NOT NULL,
FOREIGN KEY(hostel_id) REFERENCES hostels (id)
);


CREATE TABLE customers
(
 id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 room_id INT NOT NULL,
first_name VARCHAR(25) NOT NULL,
last_name VARCHAR(25) NOT NULL,
phone_number VARCHAR(20) NOT NULL,
gender VARCHAR(10) ,
email VARCHAR(25) UNIQUE NOT NULL,
FOREIGN KEY(room_id) REFERENCES rooms (id)
);



CREATE TABLE hostel_reservations
(
id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
customer_id INT NOT NULL,
room_id INT NOT NULL,
arrival_date DATE NOT NULL,
departure_date DATE NOT NULL,
price INT NOT NULL,
FOREIGN KEY (customer_id) REFERENCES customers (id),
FOREIGN KEY (room_id) REFERENCES rooms (id)
);

CREATE TABLE event_reservations
(
id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
hostel_id INT NOT NULL,
event_name VARCHAR(50) NOT NULL,
start_date DATE NOT NULL,
end_date DATE NOT NULL,
capacity INT,
description VARCHAR(250),
FOREIGN KEY (hostel_id) REFERENCES hostels (id)
);



CREATE TABLE outdoor_events
(
id INT NOT NULL PRIMARY KEY,
price INT NOT NULL,
FOREIGN KEY(id) REFERENCES event_reservations (id)
);


